version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: tunepipe
    main: ./main.go   # adapte si ton entrypoint est ailleurs, ex: ./cmd/tunepipe
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: Arnel-rah
    name: tunepipe

brews:
  - repository:
      owner: Arnel-rah
      name: homebrew-tunepipe
    homepage: "https://github.com/Arnel-rah/tunepipe"
    description: "A minimal TUI music player powered by yt-dlp"